[alembic]
script_location = alembic
sqlalchemy.url = postgresql://${ARUS_DB_USER:-arus}:${ARUS_DB_PASSWORD:-arus_secret}@${ARUS_DB_HOST:-localhost}:${ARUS_DB_PORT:-5432}/${ARUS_DB_NAME:-arus_warehouse}

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
